services:
  - type: web
    name: dialogflow-chatgpt-flask
    env: python
    buildCommand: ""  # Leave empty if no custom build steps are needed
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Ensure this is set correctly in Render's environment settings
